cvat/apps/dashboard/urls.py

# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.urls import path
from . import views

urlpatterns = [
    path('get_share_nodes', views.JsTreeView),
    path('get_os_nodes', views.JsTreeViewZtube),
    path('get_labels_nodes', views.JsTreeViewLabels),
    path('get_frameprops_nodes', views.JsTreeViewFrameProperties),
    path('get_projects_nodes', views.JsTreeViewProjects),
    path('get_labels_db', views.getLabelsViewDb),
    path('save_label_type_db', views.saveLabelType),
    path('save_frame_property_to_db', views.saveFrameProperty),
    path('create_project', views.addNewProject),
    path('create_object_storage', views.addNewObjectStorage),
    path('update_object_storage', views.updateObjectStorage),
    path('delete_object_storage', views.deleteObjectStorage),
    path('test_object_storage', views.testObjectStorage),
    path('is_admin', views.isAdmin),
    path('is_manager', views.isManager),
    path('does_task_exist/project/<int:projectId>/task/<str:taskName>', views.doesTaskExist),
    path('does_object_storage_exist/project/<int:projectId>', views.doesObjectStorageExist),
    path('has_object_storage/<int:projectId>', views.projectHasObjectStorage),
    path('get/projects', views.getProjectsFromDB),
    path('get/project/<int:projectId>/tasks/<int:page>', views.get_task_batch),
    path('get/allUsers', views.getAllUsersFromDB),
    path('get/userForProject/<str:projectName>', views.getUsersForProjectFromDB),
    path('save_users_to_projects', views.saveUsersForProjectToDB),
    path('update/status/<str:newStatus>/<int:taskId>', views.updateTaskStatus),
    path('get/userProjectRelation', views.getUsersRelatedToProjects),
    path('project/<str:projectName>/has_score', views.projectHasScore),
    path('update_label', views.updateLabel),
    path('update_label_color', views.updateLabelColor),
    path('update_attribute', views.updateAttribute),
    path('update_value', views.updateValue),
    path('delete_label', views.deleteLabel),
    path('delete_attribute', views.deleteAttribute),
    path('delete_value', views.deleteValue),
    path('update_project_name', views.updateProjectName),
    path('update/project/<str:projectName>/has_score/<str:hasScore>', views.updateProjectScore),
    path('delete_project', views.deleteProject),
    path('update_frameProperty', views.updateFrameProp),
    path('update_frameValue', views.updateFrameValue),
    path('delete_frameProp', views.deleteFrameProp),
    path('delete_frameProp_value', views.deleteFramePropValue),
    path('get/matomo', views.get_matomo),
    path('', views.DashboardView),
]

cvat/urls.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

"""CVAT URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.apps import apps
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cvat.apps.engine.urls')),
    path('dashboard/', include('cvat.apps.dashboard.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('auth/', include('cvat.apps.authentication.urls')),
    path('documentation/', include('cvat.apps.documentation.urls')),
]

if apps.is_installed('cvat.apps.tf_annotation'):
    urlpatterns.append(path('tensorflow/annotation/', include('cvat.apps.tf_annotation.urls')))

if apps.is_installed('cvat.apps.log_viewer'):
    urlpatterns.append(path('analytics/', include('cvat.apps.log_viewer.urls')))

if apps.is_installed('silk'):
    urlpatterns.append(path('profiler/', include('silk.urls')))

cvat/apps/dashboard/models.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.db import models

# Create your models here.

cvat/apps/engine/models.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.db import models
from django.conf import settings

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField, JSONField

from io import StringIO
from enum import Enum

import shlex
import csv
import re
import os

class StatusChoice(Enum):
    ANNOTATION = 'annotation'
    VALIDATION = 'validation'
    COMPLETED = 'completed'

    @classmethod
    def choices(self):
        return tuple((x.name, x.value) for x in self)

    def __str__(self):
        return self.value

class SafeCharField(models.CharField):
    def get_prep_value(self, value):
        value = super().get_prep_value(value)
        if value:
            return value[:self.max_length]
        return value

class Projects(models.Model):
    name = models.CharField(max_length=256)
    has_score = models.BooleanField(default=False)

    class Meta:
        default_permissions = ()

class Task(models.Model):
    name = SafeCharField(max_length=256)
    size = models.PositiveIntegerField()
    path = models.CharField(max_length=256)
    mode = models.CharField(max_length=32)
    owner = models.ForeignKey(User, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="owners")
    assignee = models.ForeignKey(User, null=True,  blank=True,
        on_delete=models.SET_NULL, related_name="assignees")
    bug_tracker = models.CharField(max_length=2000, blank=True, default="")
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now_add=True)
    overlap = models.PositiveIntegerField(default=0)
    z_order = models.BooleanField(default=False)
    flipped = models.BooleanField(default=False)
    source = SafeCharField(max_length=256, default="unknown")
    status = models.CharField(max_length=32, default=StatusChoice.ANNOTATION)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, default=1)
    score = models.FloatField(default=0)
    last_viewed_frame = models.PositiveIntegerField(default=0)
    video_id = models.IntegerField(default=-1)

    # Extend default permission model
    class Meta:
        default_permissions = ()
        unique_together = ['name', 'project']

    def get_upload_dirname(self):
        return os.path.join(self.path, ".upload")

    def get_data_dirname(self):
        return os.path.join(self.path, "data")

    def get_dump_path(self):
        name = re.sub(r'[\\/*?:"<>|]', '_', self.name)
        return os.path.join(self.path, "{}.dump".format(name))

    def get_log_path(self):
        return os.path.join(self.path, "task.log")

    def get_client_log_path(self):
        return os.path.join(self.path, "client.log")

    def get_image_meta_cache_path(self):
        return os.path.join(self.path, "image_meta.cache")

    def set_task_dirname(self, path):
        self.path = path
        self.save(update_fields=['path'])

    def get_task_dirname(self):
        return self.path

    def __str__(self):
        return self.name

class TaskSource(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    source_name = models.CharField(max_length=256)
    frame = models.IntegerField()

    class Meta:
        default_permissions = ()

class Watershed(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    frame = models.PositiveIntegerField()
    paintings = JSONField()
    watershed = ArrayField(ArrayField(models.IntegerField()), null=True)

    class Meta:
        default_permissions = ()

class FrameProperties(models.Model):
    prop = models.CharField(max_length=256)
    value = models.CharField(max_length=256, null=True, default=None)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    class Meta:
        default_permissions = ()

class TaskFrameSpec(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    propVal = models.ForeignKey(FrameProperties, on_delete=models.CASCADE)

    class Meta:
        default_permissions = ()

class KeyframeSpec(models.Model):
    frame = models.PositiveIntegerField()
    frameSpec = models.ForeignKey(TaskFrameSpec, on_delete=models.CASCADE)

    class Meta:
        default_permissions = ()
        
class ObjectStorages(models.Model):
    name = models.CharField(max_length=256)
    secret_key = models.CharField(max_length=256)
    access_key = models.CharField(max_length=256)
    endpoint_url = models.CharField(max_length=256, default='example.com')
    
    class Meta:
        default_permissions = ()

class Projects_Users(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)

    class Meta:
        default_permissions = ()

class Projects_ObjectStorages(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    object_storage = models.ForeignKey(ObjectStorages, on_delete=models.CASCADE)
    channels = ArrayField(models.CharField(max_length=256), null=True)

    class Meta:
        default_permissions = ()

class LabelTypes(models.Model):
    label = models.CharField(max_length=256)
    attribute = models.CharField(max_length=256, null=True, default=None)
    value = models.CharField(max_length=256, null=True, default=None)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    
    class Meta:
        default_permissions = ()

class AttributeDetails(models.Model):
    can_change = models.BooleanField(default=True)
    labelType = models.ForeignKey(LabelTypes, on_delete=models.CASCADE)
    
    class Meta:
        default_permissions = ()
        
class LabelDetails(models.Model):
    color = models.CharField(max_length=256)
    catagory = models.CharField(max_length=256, default='category')
    labelType = models.ForeignKey(LabelTypes, on_delete=models.CASCADE)
    
    class Meta:
        default_permissions = ()
        
class Segment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    start_frame = models.IntegerField()
    stop_frame = models.IntegerField()

    class Meta:
        default_permissions = ()

class Job(models.Model):
    segment = models.ForeignKey(Segment, on_delete=models.CASCADE)
    assignee = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=32, default=StatusChoice.ANNOTATION)
    max_shape_id = models.BigIntegerField(default=-1)

    class Meta:
        default_permissions = ()

class Comments(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    frame = models.PositiveIntegerField()
    comment = models.CharField(max_length=9999)
    class Meta:
        default_permissions = ()

class Label(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    name = SafeCharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        default_permissions = ()

def parse_attribute(text):
    match = re.match(r'^([~@])(\w+)=(\w+):?(.+)?$', text)
    prefix = match.group(1)
    name = match.group(3)
    if match.group(4):
        values = list(csv.reader(StringIO(match.group(4)), quotechar="'"))[0]
        type = match.group(2)
    else:
        values = []
        type = 'text'

    return {'prefix':prefix, 'type':type, 'name':name, 'values':values}

class AttributeSpec(models.Model):
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    text  = models.CharField(max_length=1024)

    class Meta:
        default_permissions = ()

    def get_attribute(self):
        return parse_attribute(self.text)

    def is_mutable(self):
        attr = self.get_attribute()
        return attr['prefix'] == '~'

    def get_type(self):
        attr = self.get_attribute()
        return attr['type']

    def get_name(self):
        attr = self.get_attribute()
        return attr['name']

    def get_default_value(self):
        attr = self.get_attribute()
        return attr['values'][0]

    def get_values(self):
        attr = self.get_attribute()
        return attr['values']

    def __str__(self):
        return self.get_attribute()['name']


class AttributeVal(models.Model):
    # TODO: add a validator here to be sure that it corresponds to self.label
    id = models.BigAutoField(primary_key=True)
    spec = models.ForeignKey(AttributeSpec, on_delete=models.CASCADE)
    value = SafeCharField(max_length=64)

    class Meta:
        abstract = True
        default_permissions = ()


class Annotation(models.Model):
    job   = models.ForeignKey(Job, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    frame = models.PositiveIntegerField()
    group_id = models.PositiveIntegerField(default=0)
    client_id = models.BigIntegerField(default=-1)

    class Meta:
        abstract = True

class Shape(models.Model):
    occluded = models.BooleanField(default=False)
    z_order = models.IntegerField(default=0)

    class Meta:
        abstract = True
        default_permissions = ()

class BoundingBox(Shape):
    id = models.BigAutoField(primary_key=True)
    xtl = models.FloatField()
    ytl = models.FloatField()
    xbr = models.FloatField()
    ybr = models.FloatField()

    class Meta:
        abstract = True
        default_permissions = ()

class PolyShape(Shape):
    id = models.BigAutoField(primary_key=True)
    points = models.TextField()

    class Meta:

cvat/apps/dashboard/templates/dashboard/task.html
<!--
    Copyright (C) 2018 Intel Corporation

    SPDX-License-Identifier: MIT
-->
<div class="dashboardTaskUI" id="dashboardTask_{{item.id}}" project="{{item.project.name}}">
    <input id="date_{{item.id}}" type="hidden" value='{{item.created_date|date:"r"}}'> <!-- date:"r" formats django date to a format js knows -->
    <input id="score_{{item.id}}" type="hidden" value="{{item.score}}">
    {% for segm in item.segment_set.all %}
        {% for job in segm.job_set.all %}
            <table style="width: 100%;">
                <tbody>
                    <tr style="width: 100%;">
                        <td style="width: 33%;">
                            <div>
                                <label class="semiBold dashboardAssignedUser" value="{{item.assignee.id}}">&#x1F464; {{item.assignee}}</label>
                            </div>
                        </td>
                        <td style="width: 37%;">
                            <center class="dashboardTitleWrapper" style="margin-top: 15px;">
                                <a 
                                    class="semiBold h1 dashboardTaskNameLabel selectable" 
                                    href="{{base_url}}?id={{job.id}}" 
                                    style="font: 400 13.3333px Arial; font-size: 40px;"
                                    title="{{ item.name }}"> 
                                    {{ item.name|truncatechars:13 }} 
                                </a>
                                {% if item.priority %}
                                    <span style="font-family: Arial;">({{ item.priority }})</span>
                                {% else %}
                                    <span style="font-family: Arial;">(Score: {{ item.score }})</span>
                                {% endif %}
                            </center>
                        </td>
                        <td style="width: 30%;"></td>
                    </tr>
                </tbody>
            </table>
            <a href="{{base_url}}?id={{job.id}}"><div class="dashboardTaskIntro" style='background-image: url("/get/task/{{item.id}}/frame/0")'></div></a>
        {% endfor %}
    {% endfor %}
    <div class="dashboardButtonsUI">
        <button class="dashboardDumpAnnotation semiBold dashboardButtonUI"> Dump Annotation </button>
        <button class="dashboardUploadAnnotation semiBold dashboardButtonUI"> Upload Annotation </button>
        <button class="dashboardUpdateTask semiBold dashboardButtonUI isManager"> Update Task </button>
        <button class="dashboardDeleteTask semiBold dashboardButtonUI isManager"> Delete Task </button>
         {% if item.bug_tracker %}
            <button class="dashboardOpenTrackerButton semiBold dashboardButtonUI"> Open Bug Tracker </button>
            <a class="dashboardBugTrackerLink" href='{{item.bug_tracker}}' style="display: none;"> </a>
        {% endif %}
    </div>
    <div class="dashboardValidationUI">
        {% if item.status == "annotation" %}
            <label class="semiBold h1 selectable" style="display:block; margin-bottom:10px;"> Validation: </label>
            <button class="dashboardRequestValidation semiBold dashboardButtonUI"> Request Validation </button>
            {% if item.has_comments %}
                <label class="semiBold selectable dashboardCommentLabel">This task returned with comments...</label>
            {% endif %}
        {% elif item.status == "validation" %}
            <label class="semiBold h1 selectable isManager" style="display:block; margin-bottom:10px;"> Validation: </label>
            <div>
                <button class="dashboardFinishTask semiBold dashboardValidationButton dashboardAcceptValidation isManager"> ✓ </button>
                <button class="dashboardRejectRequest semiBold dashboardValidationButton dashboardRejectValidation isManager"> ✗ </button>
            </div>
            {% if item.has_comments %}
                <label class="semiBold selectable dashboardCommentLabel">You might want to review existing comments before accepting.</label>
            {% endif %}
        {% else %}
            <label class="semiBold h1 selectable isManager" style="display:block; margin-bottom:10px;"> Validation: </label>
            <button class="semiBold dashboardRejectValidation isManager dashboardButtonUI"> Re-Open Task </button>
            {% if item.has_comments %}
                <label class="semiBold selectable dashboardCommentLabel">Re-opening the task will reload its comments.</label>
            {% endif %}
        {% endif %}
    </div>
</div>